### ISSUE TITLE
Readme updates

### ISSUE THREAD

**Issue by levice14** [CloudSlang/cs-intellij-plugin#16]
- seems to have formatting issues - e.g.:
```
##Table of Contents

Features
Installation
Getting Started
##Features

CloudSlang file type support (.sl, .sl.yaml, .sl.yml, .prop.sl)
Live templates (e.g: flow, operation, input, output, step, for, java_action etc.)
Completion support for CloudSlang keywords
Syntax highlighting
CloudSlang file validation and error highlighting
##Installation
```

- should have a `how to build section`

@tethryus WDYT?

**Comment by tethryus** [comment]
@Bonczidai I will add the documentation needed for the new gradle implementation and how to test everything.

**Comment by tethryus** [comment]
The formatting issues come from updates in Markdown that do not use <br /> anymore. Will be fixed.
