### ISSUE TITLE
Error message problems

### ISSUE THREAD

**Issue by levice14** [CloudSlang/cs-intellij-plugin#5]
- nulls?
- description problem should be warning not error

![screenshot_4](https://cloud.githubusercontent.com/assets/8058961/22881230/471e9e2e-f1ee-11e6-94ac-891c63afbbfb.png)

@tethryus @lucian-cm @ligiacentea WDYT?

**Comment by andreivasiletruta** [comment]
I think the null is certainly something to be fixed.
As for warning vs error - I guess it depends on what happens at runtime

**Comment by tethryus** [comment]
It should be an error since the validation is enforced. If it is left as a warning, it can be overlooked, and in case of multiple operations/flows, you would have to recheck all of them after creating a pull request. This can be discussed.

**Comment by levice14** [comment]
checkstyle enforcements are usually optional - it should be configurable in that case with default to warning - they are comments - I wouldn't be so strict by default

IMHO
