### ISSUE TITLE
The flow template has a description based misspelling 

### ISSUE THREAD

**Issue by andreivasiletruta** [CloudSlang/cs-intellij-plugin#6]
The flow template mentions "occured" instead of "occurred".
Check below:

########################################################################################################################
#!!
#! @description: Generated flow description
#!
#! @input input_1: Generated description
#! @input input_2: Generated description
#!
#! @output output_1: Generated description
#!
#! @result SUCCESS: Flow completed successfully.
#! @result FAILURE: Failure **occured** during execution.
#!!#
########################################################################################################################

**Comment by tethryus** [comment]
@andreivasiletruta Thanks for catching that, In the next release this fix will be included.

**Comment by tethryus** [comment]
@andreivasiletruta This issue has been fixed in PR https://github.com/CloudSlang/cs-intellij-plugin/pull/21/files

**Comment by andreivasiletruta** [comment]
Changes have been merged to master. Closing the issue.
